### ISSUE TITLE
Slows Google News page loading hugely.

### ISSUE THREAD

**Issue by daver1691** [luben/load-progress-bar#10]
Slows Google News page loading hugely. I've tested this several times enabled and disabled, and it's quite repeatable. It hammers Google News for some reason. 2 to 3 times slower on page loading.

**Comment by luben** [comment]
I will take a look. Thanks for reporting.

**Comment by luben** [comment]
Yes, looks like dynamically loading all the news creates a lot of work for the progress bar. I have an idea how to solve it.

**Comment by luben** [comment]
Can you try the new version? I think it should be lot lighter.

**Comment by Siva981** [comment]
Hi Luben,

The new version has broken the customization options (Color and Thickness) of the add-on. I have set "Green" color with "Maximum" thickness. However, the add-on displays the default "Red" color with "Minimum" thickness for most of the websites. It displays my custom color and thickness only on 1 or 2 websites. For example, it displays the default options even for github.com website. But it displays my custom color for https://www.speedtest.net/ . Hopefully you can get this sorted out. 

Thanks in Advance,
Siva
Chennai
India
(I am using latest Firefox + Windows 7 Home Premium)

**Comment by luben** [comment]
Thank, I will look at it.

**Comment by luben** [comment]
@Siva981 , pushed a new version with the fix

**Comment by Siva981** [comment]
It is still not working. Now even the https://www.speedtest.net/ website is displaying the default.

Do I need to close Firefox and open it again?

**Comment by luben** [comment]
Hmm, confirmed. I will look what's the problem.

**Comment by luben** [comment]
I think I have fixed it now in 0.14. Please confirm.

**Comment by luben** [comment]
hmm, another fail. Not the defaults don't get applied

**Comment by luben** [comment]
ops, my bad, it's applied. 0.14 looks good

**Comment by Siva981** [comment]
Yes, it is working now. Thank you for the quick updates!

**Comment by luben** [comment]
@daver1691 , does it perform better now?

**Comment by daver1691** [comment]
I refreshed Google News with and without the bar enabled, then repeated 10 times to get a reasonably accurate average. Disabled: 5.8 seconds, enabled: 7.1 seconds. This is much better than it was before but still high for a minimal single-purpose addon like this. I don't understand why an addon like this should have any detectable delay at all.

**Comment by luben** [comment]
@daver1691 , I think applying the style changes and the transition animations cause the slowdown. I have just published v0.15 that have an option to disable the progress bar growth animation. Can you check if running with "smooth: no" will improves the performance for you?

**Comment by daver1691** [comment]
Sorry, no. Another average of 10, and no significant difference with smooth:no. Disabled: 5.8  seconds, enabled: 7.3 seconds.

**Comment by luben** [comment]
OK, I guess then the transition vs. no transition it not the problem but just updating the CSS for the progress that happens once per 250ms. I will leave the option as is, in case it helps anybody in the future.
