### ISSUE TITLE
Mention Firefox for Android in the Description

### ISSUE THREAD

**Issue by davidhedlund** [luben/load-progress-bar#11]
Firefox for Android (codenamed Fennec) has a progress bar inbuilt. Can you mention that at https://addons.mozilla.org/en-US/firefox/addon/load-progress-bar/ ? Something like this:
> This add-on adds a thin progress bar to each window while the page is still loading, like the inbuilt progress bar in Firefox for Android (codenamed Fennec).

**Comment by luben** [comment]
Good call!

**Comment by davidhedlund** [comment]
> Good call!

Thank you very much.

**Comment by davidhedlund** [comment]
By the way, I mentioned your add-ons here: https://bugzilla.mozilla.org/show_bug.cgi?id=1536932

**Comment by luben** [comment]
Thanks!

**Comment by davidhedlund** [comment]
I added your add-on to my collection https://addons.mozilla.org/en-US/firefox/collections/11536848/essential-webextensions/ and added a comment to it:
> This type of progress bar is inbuilt in Firefox for Android (codenamed Fennec). I've requested Mozilla to implement it: Implement the Firefox for Android progress bar - https://bugzilla.mozilla.org/show_bug.cgi?id=1536932

**Comment by davidhedlund** [comment]
Would you like to mention something this at https://addons.mozilla.org/en-US/firefox/addon/load-progress-bar/
> Mozilla will hopefully "Implement the Firefox for Android progress bar" (https://bugzilla.mozilla.org/show_bug.cgi?id=1536932) to Firefox in the future.

**Comment by luben** [comment]
added it

**Comment by davidhedlund** [comment]
> added it

Thank you again!
