### ISSUE TITLE
Extension causing significant performance hit

### ISSUE THREAD

**Issue by ecbrodie** [luben/load-progress-bar#12]
I've noticed a significant hit to web page loading performance on Firefox when I have this extension enabled, versus when it's disable. I'm not sure if anyone else has reported in about performance issues, or if its a known problem?

**Comment by luben** [comment]
It's not known problem. which version of Firefox are you using? Also which OS?

I guess you are using the most recent version of the extension (0.16)?

**Comment by ecbrodie** [comment]
Firefox 66.0.5
Mac OS 10.14.4
Extension version 0.16

Do you have any tips for how to debug where the exact performance hit may be coming from?

**Comment by luben** [comment]
I am not sure how to help. A few months ago I tried to optimize it so I did:

- updating progress in not less than 250ms, so at most 4 updates per second.
- not moving progress back as the new elements are requested.
- moved from gradients to updating a block element width.

There is one thing that could be CPU consuming: transitions are animated. You can switch off the animation from the add-on preferences. Just change the "Smooth" to "No". Is this improving the load-times on your side?

**Comment by ecbrodie** [comment]
@luben I just disabled the smooth rendering and it seems to have improved performance by a lot. Feel free to close this issue. I will suggest that perhaps the default for this option should be "No". Users can opt-in if they feel like their computer is performance enough to handle smooth rendering. Otherwise, I worry that people will choose to just uninstall the extension due to the issue, rather than report it and have a constructive discussion like the one here.

Thank you for the help.

**Comment by luben** [comment]
Yes, I agree that disabling the smooth animation may be better default.

I will keep the issue open to remind me to make the change.

**Comment by luben** [comment]
v0.18 changes the default to disabled
