### ISSUE TITLE
[ENHANCEMENT] Add gradient option similar to Fenix

### ISSUE THREAD

**Issue by axeltrinidade** [luben/load-progress-bar#17]
linear-gradient(90deg, #9400FF, #ba00e5, #df06b9, #e62da7, #f13b95, #f64d86, #f85f7a, #fc7169, #f9845b, #e8ab52)

![Screenshot (295)](https://user-images.githubusercontent.com/68217806/122655065-51dcd700-d16d-11eb-8833-3076fd39474e.png)

**Comment by GangstaPichu** [comment]
This would be cool. I wish it had a way to make a rainbow progress bar.

**Comment by luben** [comment]
in v0.24 there is option now for rainbow progress bar
