### ISSUE TITLE
[Request] Overlay it over the urlbar or just below it.

### ISSUE THREAD

**Issue by clifford269** [luben/load-progress-bar#23]
I'm attempting to bring classic features back to Mozilla, along with Aero design.

**Comment by luben** [comment]
I don't think this is possible with the limitations of the current extensions API

**Comment by clifford269** [comment]
What are the limitations? Can UC scripts do it then? If not, can we move it to a status bar at the bottom instead?
(I'm implying compatibility atleast with the 115 ESR for now)

**Comment by clifford269** [comment]
Also, is implementing a function to copy Urls on right clicking over them on megabar popup implementable? I invite you to contribute to my repo 
https://github.com/clifford269/FrutigerFX

![Capture](https://github.com/user-attachments/assets/352e100d-b72f-44e1-b91c-9a7c4c42a9c9)

**Comment by luben** [comment]
userChrome.css have more power than extensions to modify stuff outside of the window, but I am not sure how dynamic it can be to replicate the progress bar. UC cannot be modified or installed by extension.

**Comment by clifford269** [comment]
Yeah. UC can be given a go. I've implemented quite a few things that rely on them already.

**Comment by clifford269** [comment]
I'm currently working on how such scripts work and the modules, etc. If you could help me get a headstart, it'd be great. Are you on discord?
