### ISSUE TITLE
position: fixed; for bottom place

### ISSUE THREAD

**Issue by joextra** [luben/load-progress-bar#3]
Hello,

you should add position: fixed; for the bottom place. With absolute, the progress bar, moves with the site if you scroll before its ready with loading.

**Comment by luben** [comment]
Hmm, thanks for the bug-report. I will investigate. I when I was adding the bottom position I couldn't make it work with "position: fixed". I will try again

**Comment by luben** [comment]
Yes, you are right, it works better with "position: fixed". Fixed version is coming shortly.

**Comment by luben** [comment]
v0.5 published with the fix. Thanks for reporting it!

**Comment by joextra** [comment]
Thank you for your quick response. Now its working perfect.
