### ISSUE TITLE
Progress bar fading out upon completion

### ISSUE THREAD

**Issue by Regnander** [luben/load-progress-bar#4]
Is it possible to make the progress bar fade out when the page has finished loading instead of disappearing instantaneously? If so, perhaps it should be added as a setting for users who'd prefer the original behavior.

**Comment by luben** [comment]
Yes, that would me nice. I will look how to make it fade instead of just disappear.

**Comment by luben** [comment]
Hi,
Just sent the v0.6 for review. It should land pretty soon with the proposed change.
Thanks for the suggestion!

**Comment by Regnander** [comment]
I just updated the addon and it looks great. Thank _you_ for implementing it!
