### ISSUE TITLE
The bar is jumping back and forth on some websites

### ISSUE THREAD

**Issue by Regnander** [luben/load-progress-bar#6]
On some sites the progress bar gets a "bobbing" behavior upon loading. This is captured from Google's front page:

![bobbing progress](https://user-images.githubusercontent.com/17113053/35199018-e5d1108a-fef7-11e7-96b9-8ce344dc31ed.gif)

Why is this happening and can it be fixed?

**Comment by luben** [comment]
Yes, this happens as more loadable elements are added to the page dynamically by the scripts that are executed by the page. Imagine a page that has only one script as externally loadable element. When the script finishes loading the addon assumes that the page is 50% loaded (as the window is not yet loaded fully - it will be loaded when all the scripts finish execution). Now if this script dynamically add one image to the DOM we now assume that only 33% of the page is loaded (only the script) and two are still to be loaded - the window and the image.

So this causes the jumping back and forth of the progress - we can't know in advance how many elements will be dynamically loaded. Another UI option would be to freeze the progress bar until the actual progress catches up. I don't know if this is to be preferred as it will not represent the actual progress.

**Comment by luben** [comment]
BTW, checked on my android where the browsers usually have similar progress bar. In Firefox the progress bar freezes, in Chrome it jumps back.

**Comment by luben** [comment]
Fixed in the last release
