### ISSUE TITLE
Addon makes Firefox dev tools Inspector failed

### ISSUE THREAD

**Issue by hungpham2411** [luben/load-progress-bar#8]
Reproduce issue:
1. Enable addon Load progress bar
2. Open a webpage and open Inspector tab in Firefox dev tools
3. Refresh the webpage
4. See content of Inspector tab in Firefox dev tools, Firefox can't show html tags anymore.

Firefox Developer Edittion 61.0b5
Thanks.

**Comment by luben** [comment]
I will try with developer edition, here on the normal 61.0b5 it works fine.
