### ISSUE TITLE
Progress bar colour not sticking

### ISSUE THREAD

**Issue by ghost** [luben/load-progress-bar#9]
Load Progress Bar 0.9
Firefox 62
Linux Mint 19 x64 Cinnamon

If I change the setting for bar colour, and then close the addOn window, then, when I go back to the preference window, the colour has reverted to what it was previously.

**Comment by luben** [comment]
Do you click the "Save" button below?

**Comment by ghost** [comment]
Oh. No, I had not. That button was off the bottom of the screen . . Thanks.
